export type WidgetPosition = "left" | "right";
export type WidgetLanguage = "auto" | "en" | "es" | "pt" | "fr";
export type WidgetLauncherIcon = "whatsapp" | "chat" | "bot" | "store" | "logo";
export type WidgetFormat = "classic" | "assistant";
export type WidgetLauncherStyle = "icon" | "card";

export interface WidgetAppearance {
  format: WidgetFormat;
  accent: string;
  accentContrast: string;
  accentShadow: string;
  accentLight: string;
  accentGradient: string;
  closeColor: string;
  closeBg: string;
  brandName: string;
  brandInitial: string;
  collapsedLabel: string;
  greeting: string;
  launcherIcon: WidgetLauncherIcon;
  launcherLogoUrl: string | null;
  launcherStyle: WidgetLauncherStyle;
  bubbleSubtitle: string;
  bubbleUseThree: boolean;
  bubbleWidth: number;
  bubbleRadius: number;
  position: WidgetPosition;
  width: number;
  height: number;
  offsetX: number;
  offsetY: number;
  launcherSize: number;
  borderRadius: number;
  // New customization fields
  colorHeaderBg: string;
  colorHeaderText: string;
  colorChatBg: string;
  colorUserBubbleBg: string;
  colorUserBubbleText: string;
  colorBotBubbleBg: string;
  colorBotBubbleText: string;
  colorToggleBg: string;
  colorToggleText: string;
  colorBubbleBg: string;
  colorBubbleText: string;
  colorBubbleSubtext: string;
  colorBubbleBorder: string;
  colorBubbleGlow: string;
}

export interface WidgetConfig {
  key: string;
  chatEndpoint: string;
  language?: WidgetLanguage | string | null;
  format?: WidgetFormat | string | null;
  accent: string;
  brandName: string;
  brandInitial: string;
  collapsedLabel: string;
  greeting: string;
  humanSupportText?: string;
  launcherIcon?: WidgetLauncherIcon | string | null;
  launcherLogoUrl?: string | null;
  launcherStyle?: WidgetLauncherStyle | string | null;
  bubbleSubtitle?: string;
  bubbleUseThree?: boolean;
  bubbleWidth?: number;
  bubbleRadius?: number;
  position: WidgetPosition;
  width?: number;
  height?: number;
  offsetX?: number;
  offsetY?: number;
  launcherSize?: number;
  borderRadius?: number;
  appearance: {
    colorHeaderBg: string;
    colorHeaderText: string;
    colorChatBg: string;
    colorUserBubbleBg: string;
    colorUserBubbleText: string;
    colorBotBubbleBg: string;
    colorBotBubbleText: string;
    colorToggleBg: string;
    colorToggleText: string;
    colorBubbleBg: string;
    colorBubbleText: string;
    colorBubbleSubtext: string;
    colorBubbleBorder: string;
    colorBubbleGlow: string;
  };
}

export interface AgentRecord {
  id: string;
  is_active: boolean;
  allowed_domains: string[] | null;
  widget_accent: string | null;
  widget_brand: string | null;
  widget_label: string | null;
  widget_greeting: string | null;
  widget_human_support_text: string | null;
  widget_format: WidgetFormat | string | null;
  widget_launcher_icon: WidgetLauncherIcon | string | null;
  widget_launcher_logo_url: string | null;
  widget_launcher_style: WidgetLauncherStyle | string | null;
  widget_bubble_subtitle: string | null;
  widget_bubble_use_three: boolean | null;
  widget_bubble_width: number | null;
  widget_bubble_radius: number | null;
  language: WidgetLanguage | string | null;
  widget_position: WidgetPosition | null;
  widget_width: number | null;
  widget_height: number | null;
  widget_offset_x: number | null;
  widget_offset_y: number | null;
  widget_launcher_size: number | null;
  widget_border_radius: number | null;
  widget_color_header_bg: string | null;
  widget_color_header_text: string | null;
  widget_color_chat_bg: string | null;
  widget_color_user_bubble_bg: string | null;
  widget_color_user_bubble_text: string | null;
  widget_color_bot_bubble_bg: string | null;
  widget_color_bot_bubble_text: string | null;
  widget_color_toggle_bg: string | null;
  widget_color_toggle_text: string | null;
  widget_color_bubble_bg: string | null;
  widget_color_bubble_text: string | null;
  widget_color_bubble_subtext: string | null;
  widget_color_bubble_border: string | null;
  widget_color_bubble_glow: string | null;
}
